version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./myvolume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./myvolume:/usr/share/nginx/html
